import React from 'react';
import { InitialPaymentDetails, PremiumSourceAccount } from '../types';
import { CreditCard, Wallet, Info } from 'lucide-react';

interface PaymentAccountsFormProps {
  initialPayment: InitialPaymentDetails;
  premiumSource: PremiumSourceAccount;
  onInitialPaymentChange: (updated: InitialPaymentDetails) => void;
  onPremiumSourceChange: (updated: PremiumSourceAccount) => void;
}

export const PaymentAccountsForm: React.FC<PaymentAccountsFormProps> = ({
  initialPayment,
  premiumSource,
  onInitialPaymentChange,
  onPremiumSourceChange,
}) => {
  return (
    <div className="space-y-6">
      <div className="flex items-center gap-2 pb-3 border-b border-slate-800">
        <CreditCard className="w-4 h-4 text-amber-400" />
        <h3 className="text-sm font-semibold text-slate-200">
          Funding & Source Account Tokens
        </h3>
      </div>

      <div className="bg-amber-950/20 border border-amber-900/40 rounded-xl p-3.5 flex items-start gap-2.5 text-xs text-amber-300/90">
        <Info className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" />
        <div>
          <p className="font-semibold text-amber-300">Offline Payment Account Hash Tokens</p>
          <p className="text-amber-300/80 mt-0.5">
            The Citi OpenAPI endpoint expects hashed account tokens or customer account IDs generated by the tokenization engine.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Initial Payment Account */}
        <div className="p-4 bg-slate-900 border border-slate-800 rounded-xl space-y-3">
          <div className="flex items-center gap-2">
            <Wallet className="w-4 h-4 text-sky-400" />
            <h4 className="text-xs font-semibold text-slate-200">
              1. Initial Payment Account (initialPaymentDetails)
            </h4>
          </div>

          <div>
            <label className="block text-xs font-medium text-slate-400 mb-1">
              Source Account ID <span className="text-red-400">*</span>
            </label>
            <textarea
              id="input-initial-payment-source-id"
              rows={3}
              value={initialPayment.sourceAccountId}
              onChange={(e) => onInitialPaymentChange({ sourceAccountId: e.target.value })}
              className="w-full bg-slate-950 border border-slate-700 rounded-lg px-3 py-2 text-xs text-slate-100 font-mono focus:outline-none focus:border-blue-500 break-all"
              placeholder="3c344e38756339654972776f663745446e6d4c32486f455a4165374a476858343d"
            />
            <span className="text-[11px] text-slate-500 mt-1 block">
              Funding account used for first premium payment
            </span>
          </div>
        </div>

        {/* Recurring Premium Account */}
        <div className="p-4 bg-slate-900 border border-slate-800 rounded-xl space-y-3">
          <div className="flex items-center gap-2">
            <CreditCard className="w-4 h-4 text-emerald-400" />
            <h4 className="text-xs font-semibold text-slate-200">
              2. Recurring Premium Account (premiumSourceAccount)
            </h4>
          </div>

          <div>
            <label className="block text-xs font-medium text-slate-400 mb-1">
              Source Account ID <span className="text-red-400">*</span>
            </label>
            <textarea
              id="input-recurring-premium-source-id"
              rows={3}
              value={premiumSource.sourceAccountId}
              onChange={(e) => onPremiumSourceChange({ sourceAccountId: e.target.value })}
              className="w-full bg-slate-950 border border-slate-700 rounded-lg px-3 py-2 text-xs text-slate-100 font-mono focus:outline-none focus:border-blue-500 break-all"
              placeholder="1234567896f2b4d4d796c344e387563374a476jfhjd23478377889738343d"
            />
            <span className="text-[11px] text-slate-500 mt-1 block">
              Account used for subsequent periodic premium deductions
            </span>
          </div>
        </div>
      </div>
    </div>
  );
};
