import fs from 'fs';
import path from 'path';
import { WorkbenchCatalog, ParsedSpec, EndpointDef, XsdComplexType } from './parser';

export function generateAllArtifacts(
  catalog: WorkbenchCatalog,
  outputDir: string
): { filesGenerated: string[] } {
  const generatedFiles: string[] = [];

  const dataDir = path.join(outputDir, 'data');
  const configsDir = path.join(outputDir, 'configs');
  const componentsDir = path.join(outputDir, 'components');

  fs.mkdirSync(dataDir, { recursive: true });
  fs.mkdirSync(configsDir, { recursive: true });
  fs.mkdirSync(componentsDir, { recursive: true });

  // 1. Save data/workbench-catalog.json
  const catalogPath = path.join(dataDir, 'workbench-catalog.json');
  fs.writeFileSync(catalogPath, JSON.stringify(catalog, null, 2), 'utf-8');
  generatedFiles.push(catalogPath);

  // 1b. Save data/specs-summary.json
  const summaryPath = path.join(dataDir, 'specs-summary.json');
  const summaryData = {
    generatedAt: catalog.generatedAt,
    totalSpecs: catalog.totalSpecs,
    totalEndpoints: catalog.totalEndpoints,
    totalXsdTypes: catalog.totalXsdTypes,
    totalServers: catalog.totalServers,
    specs: catalog.specs.map(s => ({
      id: s.id,
      fileName: s.fileName,
      format: s.format,
      title: s.title,
      version: s.version,
      endpointCount: s.endpoints.length,
      serverCount: s.servers.length,
      schemasCount: s.schemasCount,
      tags: s.tags,
    })),
  };
  fs.writeFileSync(summaryPath, JSON.stringify(summaryData, null, 2), 'utf-8');
  generatedFiles.push(summaryPath);

  // 2. Generate configs/environments.ts
  const envPath = path.join(configsDir, 'environments.ts');
  const envContent = generateEnvironmentsCode(catalog.specs);
  fs.writeFileSync(envPath, envContent, 'utf-8');
  generatedFiles.push(envPath);

  // 3. Generate configs/api-clients.ts
  const clientPath = path.join(configsDir, 'api-clients.ts');
  const clientContent = generateApiClientsCode(catalog.specs);
  fs.writeFileSync(clientPath, clientContent, 'utf-8');
  generatedFiles.push(clientPath);

  // 4. Generate components/types.ts
  const typesPath = path.join(componentsDir, 'types.ts');
  const typesContent = generateTypesCode(catalog.specs);
  fs.writeFileSync(typesPath, typesContent, 'utf-8');
  generatedFiles.push(typesPath);

  // 5. Generate components/GeneratedApiExplorer.tsx
  const explorerPath = path.join(componentsDir, 'GeneratedApiExplorer.tsx');
  const explorerContent = generateApiExplorerComponentCode();
  fs.writeFileSync(explorerPath, explorerContent, 'utf-8');
  generatedFiles.push(explorerPath);

  // 6. Generate components/GeneratedXsdViewer.tsx
  const xsdViewerPath = path.join(componentsDir, 'GeneratedXsdViewer.tsx');
  const xsdViewerContent = generateXsdViewerComponentCode();
  fs.writeFileSync(xsdViewerPath, xsdViewerContent, 'utf-8');
  generatedFiles.push(xsdViewerPath);

  // 7. Generate README.md
  const readmePath = path.join(outputDir, 'README.md');
  const readmeContent = `# Automated Multi-Spec API & XSD Workbench - Generated Artifacts

This directory contains automated TypeScript clients, React components, and schema definitions generated by the Multi-Spec Workbench Generator.

## Directory Layout
- **\`data/workbench-catalog.json\`**: Comprehensive catalog of all ${catalog.totalSpecs} scanned specs, ${catalog.totalEndpoints} endpoints, and ${catalog.totalXsdTypes} XSD types.
- **\`data/specs-summary.json\`**: Lightweight summary index.
- **\`configs/environments.ts\`**: Server base URLs and environment mappings (Sandbox, Production, Mock).
- **\`configs/api-clients.ts\`**: Typed HTTP client configured with bearer token, API key, and custom header injection.
- **\`components/types.ts\`**: Generated TypeScript interfaces for data models and request/response payloads.
- **\`components/GeneratedApiExplorer.tsx\`**: Standalone React interactive endpoint testing component.
- **\`components/GeneratedXsdViewer.tsx\`**: Standalone React XSD XML schema visualizer & payload generator.

## Usage Example
\`\`\`typescript
import { createWorkbenchClient } from './configs/api-clients';

const client = createWorkbenchClient({
  baseUrl: 'https://sandbox.api.citibank.com',
  apiKey: 'YOUR_API_KEY',
  bearerToken: 'YOUR_BEARER_TOKEN'
});

const result = await client.request({
  method: 'GET',
  path: '/v1/accounts',
});
console.log(result);
\`\`\`
`;
  fs.writeFileSync(readmePath, readmeContent, 'utf-8');
  generatedFiles.push(readmePath);

  return { filesGenerated: generatedFiles };
}

function generateEnvironmentsCode(specs: ParsedSpec[]): string {
  const envMap: Record<string, any> = {};

  for (const s of specs) {
    if (s.servers && s.servers.length > 0) {
      envMap[s.id] = {
        title: s.title,
        format: s.format,
        servers: s.servers,
      };
    }
  }

  return `/**
 * Auto-generated Environments & Base URLs
 * Generated: ${new Date().toISOString()}
 */

export interface ServerConfig {
  url: string;
  description: string;
  environment: 'production' | 'sandbox' | 'mock' | 'custom';
}

export interface SpecEnvironments {
  title: string;
  format: string;
  servers: ServerConfig[];
}

export const SPEC_ENVIRONMENTS: Record<string, SpecEnvironments> = ${JSON.stringify(envMap, null, 2)};

export function getDefaultBaseUrl(specId: string): string {
  const spec = SPEC_ENVIRONMENTS[specId];
  if (!spec || !spec.servers || spec.servers.length === 0) {
    return 'https://sandbox.api.example.com';
  }
  const sandbox = spec.servers.find(s => s.environment === 'sandbox');
  return (sandbox || spec.servers[0]).url;
}
`;
}

function generateApiClientsCode(specs: ParsedSpec[]): string {
  return `/**
 * Auto-generated Multi-Spec API Client
 * Generated: ${new Date().toISOString()}
 */

export interface ClientConfig {
  baseUrl: string;
  apiKey?: string;
  bearerToken?: string;
  customHeaders?: Record<string, string>;
  timeoutMs?: number;
}

export interface RequestOptions {
  method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH' | 'OPTIONS' | 'HEAD';
  path: string;
  queryParams?: Record<string, any>;
  pathParams?: Record<string, any>;
  headers?: Record<string, string>;
  body?: any;
}

export interface ApiResponse<T = any> {
  ok: boolean;
  status: number;
  statusText: string;
  data: T;
  headers: Record<string, string>;
  durationMs: number;
}

export class WorkbenchApiClient {
  private config: ClientConfig;

  constructor(config: ClientConfig) {
    this.config = {
      timeoutMs: 30000,
      ...config,
    };
  }

  public updateConfig(newConfig: Partial<ClientConfig>) {
    this.config = { ...this.config, ...newConfig };
  }

  public async request<T = any>(options: RequestOptions): Promise<ApiResponse<T>> {
    let targetUrl = options.path;

    // Substitute path params
    if (options.pathParams) {
      for (const [key, val] of Object.entries(options.pathParams)) {
        targetUrl = targetUrl.replace(new RegExp(\`\\\\{\${key}\\\\}|:\${key}\`, 'g'), encodeURIComponent(String(val)));
      }
    }

    if (!targetUrl.startsWith('http://') && !targetUrl.startsWith('https://')) {
      const base = this.config.baseUrl.endsWith('/') ? this.config.baseUrl.slice(0, -1) : this.config.baseUrl;
      const subPath = targetUrl.startsWith('/') ? targetUrl : \`/\${targetUrl}\`;
      targetUrl = \`\${base}\${subPath}\`;
    }

    if (options.queryParams && Object.keys(options.queryParams).length > 0) {
      const urlObj = new URL(targetUrl);
      for (const [k, v] of Object.entries(options.queryParams)) {
        if (v !== undefined && v !== null && v !== '') {
          urlObj.searchParams.append(k, String(v));
        }
      }
      targetUrl = urlObj.toString();
    }

    const headers: Record<string, string> = {
      'Accept': 'application/json',
      'Content-Type': 'application/json',
      ...this.config.customHeaders,
      ...options.headers,
    };

    if (this.config.apiKey) {
      headers['x-api-key'] = this.config.apiKey;
    }

    if (this.config.bearerToken) {
      headers['Authorization'] = \`Bearer \${this.config.bearerToken}\`;
    }

    const startTime = performance.now();

    const fetchInit: RequestInit = {
      method: options.method,
      headers,
    };

    if (options.body && ['POST', 'PUT', 'PATCH'].includes(options.method)) {
      fetchInit.body = typeof options.body === 'string' ? options.body : JSON.stringify(options.body);
    }

    try {
      const res = await fetch(targetUrl, fetchInit);
      const durationMs = Math.round(performance.now() - startTime);

      const respHeaders: Record<string, string> = {};
      res.headers.forEach((val, key) => {
        respHeaders[key] = val;
      });

      let data: any;
      const contentType = res.headers.get('content-type') || '';
      if (contentType.includes('application/json')) {
        try {
          data = await res.json();
        } catch {
          data = await res.text();
        }
      } else {
        data = await res.text();
      }

      return {
        ok: res.ok,
        status: res.status,
        statusText: res.statusText,
        data,
        headers: respHeaders,
        durationMs,
      };
    } catch (err: any) {
      const durationMs = Math.round(performance.now() - startTime);
      return {
        ok: false,
        status: 0,
        statusText: err.name || 'Network Error',
        data: { error: err.message } as any,
        headers: {},
        durationMs,
      };
    }
  }
}

export function createWorkbenchClient(config: ClientConfig): WorkbenchApiClient {
  return new WorkbenchApiClient(config);
}
`;
}

function generateTypesCode(specs: ParsedSpec[]): string {
  let code = `/**
 * Auto-generated TypeScript Definitions from Multi-Spec Catalog
 * Generated: ${new Date().toISOString()}
 */

export interface GenericApiPayload {
  [key: string]: any;
}
`;

  for (const spec of specs) {
    const cleanSpecName = spec.id.replace(/[^a-zA-Z0-9]/g, '');

    // Generate models for schemas
    if (spec.rawSchemas && Object.keys(spec.rawSchemas).length > 0) {
      code += `\n/* =========================================================\n * Models for: ${spec.title} (${spec.fileName})\n * ========================================================= */\n`;
      for (const [schemaName, schemaObj] of Object.entries<any>(spec.rawSchemas)) {
        const cleanName = `${cleanSpecName}_${schemaName.replace(/[^a-zA-Z0-9]/g, '')}`;
        if (!schemaObj || typeof schemaObj !== 'object') continue;

        code += `\n/**\n * ${schemaObj.description || schemaName}\n */\n`;
        code += `export interface ${cleanName} {\n`;

        const props = schemaObj.properties || {};
        const required = Array.isArray(schemaObj.required) ? schemaObj.required : [];

        if (Object.keys(props).length === 0) {
          code += `  [key: string]: any;\n`;
        } else {
          for (const [propName, propObj] of Object.entries<any>(props)) {
            const isReq = required.includes(propName);
            let propType = 'string';
            if (propObj.type === 'integer' || propObj.type === 'number') propType = 'number';
            else if (propObj.type === 'boolean') propType = 'boolean';
            else if (propObj.type === 'array') propType = 'any[]';
            else if (propObj.type === 'object') propType = 'Record<string, any>';
            else if (propObj.$ref) propType = 'any';

            code += `  /** ${propObj.description || ''} */\n`;
            const isValidId = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(propName);
            const safeKey = isValidId ? propName : JSON.stringify(propName);
            code += `  ${safeKey}${isReq ? '' : '?'}: ${propType};\n`;
          }
        }
        code += `}\n`;
      }
    }

    // Generate models for XSD
    if (spec.xsdDetails && spec.xsdDetails.complexTypes.length > 0) {
      code += `\n/* =========================================================\n * XSD Types for: ${spec.fileName}\n * ========================================================= */\n`;
      for (const ct of spec.xsdDetails.complexTypes.slice(0, 50)) { // top 50 to avoid overly giant file
        const cleanCtName = ct.name.replace(/[^a-zA-Z0-9]/g, '');
        code += `\n/**\n * XSD ComplexType: ${ct.name}\n * ${ct.documentation || ''}\n */\n`;
        code += `export interface ${cleanCtName} {\n`;
        if (ct.elements.length === 0 && ct.attributes.length === 0) {
          code += `  [key: string]: any;\n`;
        } else {
          for (const el of ct.elements) {
            code += `  /** ${el.documentation || ''} (min: ${el.minOccurs}, max: ${el.maxOccurs}) */\n`;
            code += `  ${el.name}?: string | any;\n`;
          }
          for (const attr of ct.attributes) {
            code += `  /** Attribute: ${attr.documentation || ''} */\n`;
            code += `  '@_${attr.name}'?: string;\n`;
          }
        }
        code += `}\n`;
      }
    }
  }

  return code;
}

function generateApiExplorerComponentCode(): string {
  return `import React, { useState } from 'react';
import { Play, Copy, Check, Terminal, Globe, Send, RefreshCw } from 'lucide-react';

export interface EndpointRunnerProps {
  specTitle: string;
  baseUrl: string;
  path: string;
  method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH';
  summary?: string;
  parameters?: Array<{ name: string; in: string; required?: boolean; type?: string; default?: any }>;
  defaultBody?: any;
  onExecute?: (options: any) => Promise<any>;
}

export const GeneratedApiEndpointTester: React.FC<EndpointRunnerProps> = ({
  specTitle,
  baseUrl,
  path,
  method,
  summary,
  parameters = [],
  defaultBody,
  onExecute,
}) => {
  const [targetUrl, setTargetUrl] = useState(baseUrl);
  const [paramValues, setParamValues] = useState<Record<string, string>>({});
  const [bodyText, setBodyText] = useState(defaultBody ? JSON.stringify(defaultBody, null, 2) : '');
  const [loading, setLoading] = useState(false);
  const [response, setResponse] = useState<any>(null);
  const [copied, setCopied] = useState(false);

  const handleParamChange = (name: string, val: string) => {
    setParamValues(prev => ({ ...prev, [name]: val }));
  };

  const handleRun = async () => {
    setLoading(true);
    setResponse(null);

    const queryParams: Record<string, string> = {};
    const pathParams: Record<string, string> = {};
    const headers: Record<string, string> = {};

    parameters.forEach(p => {
      const val = paramValues[p.name];
      if (val !== undefined && val !== '') {
        if (p.in === 'path') pathParams[p.name] = val;
        else if (p.in === 'query') queryParams[p.name] = val;
        else if (p.in === 'header') headers[p.name] = val;
      }
    });

    let bodyPayload: any = undefined;
    if (['POST', 'PUT', 'PATCH'].includes(method) && bodyText) {
      try {
        bodyPayload = JSON.parse(bodyText);
      } catch {
        bodyPayload = bodyText;
      }
    }

    if (onExecute) {
      try {
        const res = await onExecute({
          baseUrl: targetUrl,
          path,
          method,
          queryParams,
          pathParams,
          headers,
          body: bodyPayload,
        });
        setResponse(res);
      } catch (err: any) {
        setResponse({ ok: false, error: err.message });
      }
    } else {
      // Mock execution fallback
      setTimeout(() => {
        setResponse({
          ok: true,
          status: 200,
          statusText: 'OK (Mock)',
          data: {
            message: 'Endpoint executed successfully in mock preview environment',
            endpoint: path,
            method,
            timestamp: new Date().toISOString(),
          },
          durationMs: 42,
        });
        setLoading(false);
      }, 500);
      return;
    }

    setLoading(false);
  };

  const copyCurl = () => {
    const curl = \`curl -X \${method} "\${targetUrl}\${path}" -H "Content-Type: application/json"\`;
    navigator.clipboard.writeText(curl);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="bg-[#161B22] border border-[#30363D] rounded-xl p-5 space-y-4 text-white">
      <div className="flex items-center justify-between border-b border-[#30363D] pb-3">
        <div className="flex items-center space-x-3">
          <span className={\`px-2.5 py-1 rounded text-xs font-bold \${
            method === 'GET' ? 'bg-blue-500/20 text-blue-400 border border-blue-500/30' :
            method === 'POST' ? 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/30' :
            method === 'PUT' ? 'bg-amber-500/20 text-amber-400 border border-amber-500/30' :
            'bg-rose-500/20 text-rose-400 border border-rose-500/30'
          }\`}>
            {method}
          </span>
          <span className="font-mono text-sm text-gray-200">{path}</span>
        </div>
        <div className="flex items-center space-x-2">
          <button
            onClick={copyCurl}
            className="flex items-center space-x-1 px-2.5 py-1 bg-[#21262D] hover:bg-[#30363D] text-xs text-gray-300 rounded border border-[#30363D]"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            <span>cURL</span>
          </button>
          <button
            onClick={handleRun}
            disabled={loading}
            className="flex items-center space-x-1.5 px-3 py-1 bg-[#238636] hover:bg-[#2ea043] text-xs font-medium text-white rounded transition"
          >
            {loading ? <RefreshCw className="w-3.5 h-3.5 animate-spin" /> : <Play className="w-3.5 h-3.5 fill-current" />}
            <span>Run Test</span>
          </button>
        </div>
      </div>

      {summary && <p className="text-xs text-gray-400">{summary}</p>}

      {/* Target Base URL Input */}
      <div>
        <label className="block text-xs font-medium text-gray-400 mb-1">Target Base URL</label>
        <input
          type="text"
          value={targetUrl}
          onChange={(e) => setTargetUrl(e.target.value)}
          className="w-full bg-[#0D1117] border border-[#30363D] rounded px-3 py-1.5 text-xs text-gray-200 font-mono focus:border-blue-500 outline-none"
        />
      </div>

      {/* Parameters */}
      {parameters.length > 0 && (
        <div className="space-y-2">
          <label className="block text-xs font-semibold text-gray-300">Parameters ({parameters.length})</label>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
            {parameters.map((p) => (
              <div key={p.name} className="bg-[#0D1117] p-2 rounded border border-[#30363D]">
                <div className="flex justify-between items-center text-[11px] mb-1">
                  <span className="font-mono text-blue-400">{p.name}</span>
                  <span className="text-gray-500 text-[10px] uppercase">{p.in}</span>
                </div>
                <input
                  type="text"
                  placeholder={p.default || \`value for \${p.name}\`}
                  value={paramValues[p.name] || ''}
                  onChange={(e) => handleParamChange(p.name, e.target.value)}
                  className="w-full bg-[#161B22] border border-[#30363D] rounded px-2 py-1 text-xs text-gray-200 font-mono outline-none"
                />
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Request Body */}
      {['POST', 'PUT', 'PATCH'].includes(method) && (
        <div>
          <label className="block text-xs font-semibold text-gray-300 mb-1">Request Body (JSON)</label>
          <textarea
            rows={4}
            value={bodyText}
            onChange={(e) => setBodyText(e.target.value)}
            className="w-full bg-[#0D1117] border border-[#30363D] rounded p-2 text-xs font-mono text-emerald-300 outline-none"
          />
        </div>
      )}

      {/* Response Panel */}
      {response && (
        <div className="bg-[#0D1117] border border-[#30363D] rounded-lg p-3 space-y-2">
          <div className="flex items-center justify-between text-xs border-b border-[#30363D] pb-1.5">
            <span className="font-medium text-gray-400">Response</span>
            <div className="flex items-center space-x-2">
              <span className={\`font-mono font-bold px-1.5 py-0.5 rounded text-[11px] \${
                response.ok ? 'bg-emerald-500/20 text-emerald-400' : 'bg-rose-500/20 text-rose-400'
              }\`}>
                {response.status || (response.ok ? '200 OK' : 'FAILED')}
              </span>
              {response.durationMs !== undefined && (
                <span className="text-gray-500 text-[11px]">{response.durationMs}ms</span>
              )}
            </div>
          </div>
          <pre className="text-[11px] font-mono text-gray-300 max-h-60 overflow-auto whitespace-pre-wrap">
            {JSON.stringify(response.data || response, null, 2)}
          </pre>
        </div>
      )}
    </div>
  );
};
`;
}

function generateXsdViewerComponentCode(): string {
  return `import React, { useState } from 'react';
import { FileCode, ChevronRight, ChevronDown, Copy, Check, Sparkles } from 'lucide-react';

export interface XsdTypeNode {
  name: string;
  documentation?: string;
  elements?: Array<{ name: string; type?: string; documentation?: string; minOccurs?: any; maxOccurs?: any }>;
  attributes?: Array<{ name: string; type?: string; documentation?: string }>;
}

export interface GeneratedXsdViewerProps {
  schemaName: string;
  targetNamespace?: string;
  complexTypes: XsdTypeNode[];
}

export const GeneratedXsdViewer: React.FC<GeneratedXsdViewerProps> = ({
  schemaName,
  targetNamespace,
  complexTypes,
}) => {
  const [selectedType, setSelectedType] = useState<XsdTypeNode | null>(complexTypes[0] || null);
  const [search, setSearch] = useState('');
  const [copied, setCopied] = useState(false);

  const filtered = complexTypes.filter(ct =>
    ct.name.toLowerCase().includes(search.toLowerCase()) ||
    (ct.documentation && ct.documentation.toLowerCase().includes(search.toLowerCase()))
  );

  const generateSampleXml = (node: XsdTypeNode): string => {
    const attrs = (node.attributes || []).map(a => \` \${a.name}="sample_\${a.type || 'string'}"\`).join('');
    if (!node.elements || node.elements.length === 0) {
      return \`<\${node.name}\${attrs}>SampleValue</\${node.name}>\`;
    }
    const children = node.elements.map(el => \`  <\${el.name}>\${el.type || 'string_value'}</\${el.name}>\`).join('\\n');
    return \`<\${node.name}\${attrs}>\\n\${children}\\n</\${node.name}>\`;
  };

  const copyXml = () => {
    if (!selectedType) return;
    navigator.clipboard.writeText(generateSampleXml(selectedType));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="bg-[#161B22] border border-[#30363D] rounded-xl p-5 text-white space-y-4">
      <div className="flex items-center justify-between border-b border-[#30363D] pb-3">
        <div>
          <h3 className="font-semibold text-base flex items-center space-x-2">
            <FileCode className="w-5 h-5 text-purple-400" />
            <span>{schemaName}</span>
          </h3>
          {targetNamespace && <p className="text-xs text-gray-400">Namespace: {targetNamespace}</p>}
        </div>
        <span className="text-xs px-2.5 py-1 bg-purple-500/20 text-purple-300 border border-purple-500/30 rounded-full font-mono">
          {complexTypes.length} Types
        </span>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {/* Left List */}
        <div className="space-y-2">
          <input
            type="text"
            placeholder="Filter types..."
            value={search}
            onChange={e => setSearch(e.target.value)}
            className="w-full bg-[#0D1117] border border-[#30363D] rounded px-3 py-1.5 text-xs text-gray-200 outline-none"
          />
          <div className="max-h-96 overflow-y-auto space-y-1 pr-1">
            {filtered.map(ct => (
              <button
                key={ct.name}
                onClick={() => setSelectedType(ct)}
                className={\`w-full text-left px-2.5 py-1.5 rounded text-xs truncate transition \${
                  selectedType?.name === ct.name
                    ? 'bg-purple-600/30 text-purple-200 border border-purple-500/50'
                    : 'text-gray-300 hover:bg-[#21262D]'
                }\`}
              >
                {ct.name}
              </button>
            ))}
          </div>
        </div>

        {/* Right Details */}
        <div className="md:col-span-2 bg-[#0D1117] border border-[#30363D] rounded-lg p-4 space-y-3">
          {selectedType ? (
            <>
              <div className="flex items-center justify-between border-b border-[#30363D] pb-2">
                <div>
                  <h4 className="font-mono text-sm text-purple-300 font-semibold">{selectedType.name}</h4>
                  {selectedType.documentation && (
                    <p className="text-xs text-gray-400 mt-1">{selectedType.documentation}</p>
                  )}
                </div>
                <button
                  onClick={copyXml}
                  className="flex items-center space-x-1 px-2 py-1 bg-[#21262D] hover:bg-[#30363D] text-xs text-gray-300 rounded border border-[#30363D]"
                >
                  {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                  <span>Copy XML</span>
                </button>
              </div>

              {/* Elements Table */}
              <div>
                <h5 className="text-xs font-semibold text-gray-300 mb-1.5">Child Elements ({selectedType.elements?.length || 0})</h5>
                <div className="max-h-48 overflow-y-auto border border-[#30363D] rounded divide-y divide-[#30363D]">
                  {(selectedType.elements || []).map(el => (
                    <div key={el.name} className="p-2 text-xs flex items-center justify-between">
                      <span className="font-mono text-emerald-400 font-medium">{el.name}</span>
                      <span className="text-gray-400 font-mono text-[11px]">{el.type || 'string'}</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Generated XML Preview */}
              <div>
                <h5 className="text-xs font-semibold text-gray-300 mb-1 flex items-center space-x-1">
                  <Sparkles className="w-3.5 h-3.5 text-amber-400" />
                  <span>Synthesized Sample XML</span>
                </h5>
                <pre className="bg-[#161B22] p-3 rounded text-[11px] font-mono text-amber-300 max-h-40 overflow-auto border border-[#30363D]">
                  {generateSampleXml(selectedType)}
                </pre>
              </div>
            </>
          ) : (
            <p className="text-xs text-gray-500">Select a type on the left to inspect.</p>
          )}
        </div>
      </div>
    </div>
  );
};
`;
}
